### ISSUE TITLE
SDK build error when libtensorflow-lite-dev is added to TOOLCHAIN_TARGET_TASK

### ISSUE THREAD

**Issue by pirazor** [NobuoTsukamoto/meta-tensorflow-lite#64] opened 2023-08-08 17:26 UTC
I am trying add tensorflow-lite-dev to my toolchain. But I get file clash errors for Flatbuffers, Abseil-cpp, and Eigen3 libraries. 

when I add the following to my local.config.
`TOOLCHAIN_TARGET_TASK:append += " opencv-dev gtk+3-dev libtensorflow-lite-dev libedgetpu-std-dev" `

This is an example error during meta-toolchain-b2qt-embedded-qt6-sdk-1.0-r0 do_populate_sdk:
`check_data_file_clashes: Package libtensorflow-lite-dev wants to install file /home/vision2x/b2qt-yocto/6.6/build-raspberrypi4-64/tmp/work/cortexa72-poky-linux/meta-toolchain-b2qt-embedded-qt6-sdk/1.0-r0/sdk/image/usr/local/oe-sdk-hardcoded-buildpath/sysroots/cortexa72-poky-linux/usr/include/eigen3/Eigen/src/Eigenvalues/EigenSolver.h`

How can I solve these installation conflicts ?

**Comment by NobuoTsukamoto** [comment] 2023-08-10 10:36
Sorry for the late reply.

Can you give me the information I need to reproduce? I have never built with meta-toolchain-b2qt-embedded-qt6-sdk.
I would appreciate it if you could tell me the version etc.

When `bitbake -c populate_sdk core-image-minimal` on the mickledore branch, no errors occurred.

**Comment by pirazor** [comment] 2023-08-10 15:39
Thank you @NobuoTsukamoto for your response. I am trying to use the Boot2QT configurations for RaspberryPi4-64. I am also using the Mickledore branch. This is my config file:
```
DISTRO_FEATURES:remove = " webengine "
FORTRAN:forcevariable = ",fortran"
MACHINE ?= "raspberrypi4-64"
VIDEO_CAMERA = "1"
DISABLE_RPI_BOOT_LOGO = "1"
DISABLE_SPLASH = "1"
ENABLE_UART = "1"
DISABLE_OVERSCAN = "1"
VC4DTBO = "vc4-fkms-v3d"

IMAGE_INSTALL:append += " opencv gtk+3 libtensorflow-lite python3-tensorflow-lite libedgetpu-std "
IMAGE_FEATURES:append += " package-management"
PACKAGECONFIG:append:pn-opencv += " python3 samples gstreamer gtk dnn "
TOOLCHAIN_TARGET_TASK:append += " opencv-dev gtk+3-dev libtensorflow-lite-dev libedgetpu-std-dev"`
```
When I build the image, I don't get any errors (`bitbake b2qt-embedded-qt6-image` ). But when I do build SDK, I get file clash errors with libtensorflow-lite-dev saying libflatbuffers-dev is also trying to install xxx. I think Yocto is more assertive for file conflicts when populating SDK. 

Maybe in your case Flatbuffers Abseil and Eigen packages inside the OpenEmbedded recipe are not necessarily populated in your sdk ?

**Comment by NobuoTsukamoto** [comment] 2023-08-12 06:10
I cannot reproduce the error. I get an error before running bitbake.
You reported `mickledore` branch, is that correct?
```
$ repo init -u git://code.qt.io/yocto/boot2qt-manifest -m v6.5.2.xml
$ repo sync
$ cd sources/
$ git clone -b mickledore https://github.com/NobuoTsukamoto/meta-tensorflow-lite.git
$ cd ../
$ export MACHINE=raspberrypi4-64 && source ./setup-environment.sh
$ bitbake-layers add-layer ../sources/meta-tensorflow-lite/

ERROR: Layer meta-tensorflow-lite is not compatible with the core layer which only supports these series: langdale (layer is compatible with mickledore)
ERROR: Parse failure with the specified layer added, exiting.
```

**Comment by pirazor** [comment] 2023-08-16 17:42
Thank you @NobuoTsukamoto for your response. v6.6 uses the mickledore branch. 
`$ repo init -u git://code.qt.io/yocto/boot2qt-manifest -m v6.6.xml`

You should be able to reproduce the error after editting the build-raspberrypi4-64/conf/local.conf and run `bitbake meta-toolchain-b2qt-embedded-qt6-sdk`:
 `TOOLCHAIN_TARGET_TASK:append += " opencv-dev gtk+3-dev libtensorflow-lite-dev libedgetpu-std-dev"`

To shorten the build time, you may wanna also remove `DISTRO_FEATURES:remove = " webengine "`.

**Comment by NobuoTsukamoto** [comment] 2023-08-19 10:21
Fixed a conflict in libtensorflow-lite recipe in #67 pull request.
Modified not to install eigen3, abseil-cpp, flatbuffers header files and libraries.
Due to include file dependencies, additional flatbuffers recipes are required.
See the [tensorflow-lite-minimal](https://github.com/NobuoTsukamoto/meta-tensorflow-lite/pull/67/files#diff-f1cf3fcf1d84c528c346e7bfc0abe651fbe3a50232dcf2376fd44b1c2c7d67b4) recipe.

**Comment by NobuoTsukamoto** [comment] 2023-08-30 12:23
@pirazor -san
Removed flatbuffers dependency. You don't need to specify flatbuffers in your recipe.
Merged into the mickledore branch. If you have any problems, please open the issue again.

**Closed by NobuoTsukamoto** 2023-08-30 12:23 UTC
